### ISSUE TITLE
Resizable window

### ISSUE THREAD

**Issue by laochailan** [laochailan/taisei#49]
I noticed that since the change to SDL2 the window is resizable. Is that intentional?

Resizing works really fluently now and the aspect ratio is preserved, which is good. But still it seems pretty unexpected behavior for a fixed-aspect ratio game. I can imagine most of the time will accidentally resize it and make the window have black bars.

It also messes up tiling wm behavior: The wm thinks it tiles well and doesn’t create it floating by default. If I make it float, the wm doesn’t know about the best window size and uses some random size that doesn’t fit the aspect ratio.
Normally, I never have this problem with games.

Since we already have an option to set the window size, how about making it non-resizable again?

**Comment by Akaricchi** [comment]
Yes, support for resizing was an intentional change (2a296871). I suppose it should be made optional and disabled by default. I use a tiling WM as well and find it convenient that it tiles in a way that doesn't obscure any of my terminals (one of which I use to watch the game's output), and that I can use the same hotkey I use on any other window to quickly make it "fullscreen". I could also add a hotkey to quickly reset the window size for floating WMs.

The floating behaviour you described is strange though. I haven't tried it, but I'd imagine the WM shouldn't try to resize the window at all if there's a rule to have it floating on start up in your config. Which WM are you using?

**Comment by laochailan** [comment]
I use i3, I didn’t set up a rule for it to be floating at startup in the beginning (I usually don’t need that for the things I use). I just used the shortcut to make it floating which had the window already resized …

But now I have a rule and everything is fine. After thinking about it, maybe the tiling behavior is better this way as you said. Just a matter of preference :laughing:
