### ISSUE TITLE
Don’t load everything in the beginning.

### ISSUE THREAD

**Issue by laochailan** [laochailan/taisei#66]
We are having a pretty long loading time now. It will only get worse with BGM in place. So what about somehow switching to loading things stage-wise.

At the moment most of the time is spent loading the big spell backgrounds and textures for the later stages.

Those resources are already in special folders like `gfx/stage6/`, so maybe we could add something that dynamically loads and unloads the right folder them to the stage logic.
This would also make testing spells in single spell mode faster.

**Comment by Akaricchi** [comment]
Such a system should be flexible enough to preload resources for all the stages when the story mode starts (and then release them), and definitely no reloading every time one restarts a stage (think spell practice). Lag at stage transitions should be minimized.

**Comment by laochailan** [comment]
In the original Touhou you also have a little loading thing at stage transitions and it doesn’t hurt because you need some time to relax between transitions too.

Maybe the loader shouldn’t release them or release them very hesitantly so you don’t have to reload every time you enter a stage. Finally we could make it load asynchronously and add like hints when to start loading stuff (e.g. immediately after the boss explodes).

It may be a bit complicated, but the way it is now you have to wait 3 seconds every time just to load the stage6 assets which you really never need. They could also be compressed in a lossy way.

**Comment by Akaricchi** [comment]
>In the original Touhou you also have a little loading thing at stage transitions and it doesn’t hurt because you need some time to relax between transitions too.

We do give time already, our stages don't end immediately after the boss and don't start with a bullet explosion. I think it's good to have the "relax time" be consistent this way rather than making it vary with loading times. Just because Touhou has a mid-stage loading screen doesn't mean we should. I believe the best kind of loading is one you don't notice.

Asynchronous loading is certainly an attractive option, but it does impose some challenges. Pretty much none of our code is thread-safe right now so extra care will have to be taken when implementing it. But I'm not opposed to the idea if we can get it right.

This is my intermediate proposition. I think this should clean up the stage and resources related code a bit and make it easier to implement asynchronous loading later.

**Phase 1: stage mini-refactoring**

- **Get rid of the `stage*_loop` functions.** Define a `StageProcs` struct that would hold all the stage-specific function pointers that we currently pass to `stage_loop`.
- **Have `StageInfo` contain a pointer to `StageProcs`** rather than a pointer to a loop function.
- **Move handling of stage BGM and end timers to the stage event handlers**. E.g. `AT(0) play_bgm`; `AT(5000) end_stage`.
- **Have `stage_loop` take a single `StageInfo*` parameter** and set up `global.stage` by itself. Currently the caller is responsible for this due to the crappy indirect way `stage_loop` is called (from the `StageInfo.loop` functions).

**Phase 2: resources refactoring**

- **Introduce the concept of permanent and transient resources.** Add a parameter to the resource loading functions that specifies whether to load the resource as permanent or transient. Add a function that unloads all currently loaded transient resources.
    - Attempting to load an already loaded resource of any type is either a no-op or a transient-to-permanent promotion (if attempting to load as permanent). Permanent resources are never demoted to transient.
    - The permanent resources will be used mainly for stuff that's needed by the menus and loaded during initialization.
- **Add a `preload` function to `StageProcs`**. It will be responsible for loading all resources a particular stage requires in transient mode.
    - The `preload` function will always be called by `stage_loop` to ensure the stage has all the available resources by the time it starts. `stage_loop` will not free any transient resources however, that is the caller's responsibility.
    - The `preload` function may also be called any number of times prior to calling `stage_loop`, possibly asynchronously while playing another stage. In that case, the call from `stage_loop` will do nothing, because of the behaviour described above.
- **Unload all the transient resources when the game ends.** That is, when we return to the menu, not when *a stage* ends.
- Initially, have the story mode `preload` all of the six stages, until asynchronous loading is implemented.

Phase 1 is pretty much completely independent, and I think I can implement and push it straight to master soon.

>t may be a bit complicated, but the way it is now you have to wait 3 seconds every time just to load the stage6 assets which you really never need. They could also be compressed in a lossy way.

FWIW it's about 1.5s-2s on my system with gdb (timed it). Valgrind is a different story though, that really takes forever.

**Comment by laochailan** [comment]
Okay, that sounds very smart and close to what I had in mind. As long as we can avoid race conditions with the preloading, I can’t see where it would go wrong. And Phase 1 is an overdue change anyway.

**Comment by Akaricchi** [comment]
I've just implemented phase 1 in f2d385d1.

**Comment by makise-homura** [comment]
Loading time was a serious problem when BGM was loaded by ALUT; it consumed about half of a minute or more for Taisei to load (comparable to such examples as Kerbal Space Program, but we're about Taisei which is definitely simple and small in comparison to KSP). But now, after we migrated to SDL_mixer, Taisei loads about 7-10 seconds, and it looks acceptable. But... It's always good to shorten loading time, for sure.

How do we decide which resource should be transient or permanent?
Maybe we rely on path, and if it contains something like "stageX" (X=1..6), we load this resource as transient, otherwise permanent? (But it will fail in (possibly unbelievable) situation when user installs Taisei to relative path that contains "stageX" in it.)
Or we should hardcode resource list in some header file and treat every resource that is not specified there as transient?

Implementing asynchronous loading looks very nice, but it may require long debugging because of thread synchronization; to avoid this, we may split this Phase 2 to two phases 2 and 3, and implement synchronous transient resource loading/unloading, and then switch to asynchronous at Phase 3 if we decide that interstage resource loading times are too long.

**Comment by Akaricchi** [comment]
>How do we decide which resource should be transient or permanent?

My idea is to explicitly specify whether a resource should be loaded as transient or permanent by a parameter, e.g. `load_texture("path/to/texture.png", RES_TRANSIENT)`. The stage `preload` procs would contain such calls for all resources they need. We'd load stuff used by the menus in permanent mode somewhere during the initialization, before the main menu is created. I don't think the transient/permanent distinction should be based on the file name/path in any way.

**Comment by laochailan** [comment]
But why not? The only big thing that can be made transient are stage resources.

We have the file structure needed for that and it won’t be a problem if the user installs to some directory called `stage1` because we only handle filenames relative to the resource directory.

writing `load_texture("every/path", RES_TRANSIENT)` for every single texture in all kinds of places where they are needed would add another big redundant list you have to add things to whenever you add just a little thing.

Depending how they are implemented, the path based approach can be just as flexible.

**Comment by makise-homura** [comment]
Ok, so let's try to check relative path.

I feel that I may try to implement the first step in nearest days (for the beginning, without support of transient->permanent transition and async loading, of course).

**Comment by Akaricchi** [comment]
@laochailan 

>But why not? The only big thing that can be made transient are stage resources.

I don't know how far you want to go with only loading things that are necessary. Every single asset that is not used by the menus could be made transient.

>writing load_texture("every/path", RES_TRANSIENT) for every single texture in all kinds of places where they are needed would add another big redundant list you have to add things to whenever you add just a little thing.

The only place where you'd have to write that is a stage's `preload` function. The stage-specific directories in `gfx/` have like 5 files each, except for stage6 which has 10 if you exclude the svgs (why are they there by the way? Wasn't that stuff moved to a separate repo?). You could wrap the `load_texture(path, mode)` function & friends into something like a stage-specific `recurse_dir` if you hate explicit listings that much, but not all of the stage-specific assets are actually in stage-specific subdirs... What about dialogs, projectiles/particles/enemy/boss sprites/sounds that aren't used in some/most of the stages, etc.

I didn't suggest "another big redundant list", but rather a small list per state that specifies exactly what that particular stage needs.

Note, though, that none of that really matters if we just want to cut on the loading times and don't care about keeping useless stuff in memory forever.

**Comment by laochailan** [comment]
I don’t care about keeping useless stuff in the memory or loading small useless stuff.

The stage directories only contain a few files but those are a few MBs each and for me they make most of the loading time.

I probably overlooked those svgs.

Dialog graphics could then be moved into stage specific directories if they take too long to load.

And yes maybe for simplicity we should not unload anything.

**Comment by makise-homura** [comment]
Looks like it's not hard to do simple load/unload, so it's not a significant opportunity to avoid unloads till game exits completely; as far as I see now, there's no problem in classifying resources to permanent and transient regarding their path and use `load_resources(false)` and `free_resources(false)` at start and end of the whole game, and `load_resources(true)` and `free_resources(true)` at start and end of any stage (just initialize stage number before the latter pair of calls). Such bool parameter of these functions (`bool transient`) strictly defines what to load: only permanent or only transient resources, and what to unload: only transient or all resources. So, if we are under `transient == true` condition, there will be called some kind of `delete_transient_elements()` instead of `delete_all_elements()`, and `recurse_dir()` will load only files that have `stageX` in their relative path (which have to be ignored if we load permanent resources).

Also it adds some kind of universality: we may have sfx, bgm, models, shaders, gfx, etc. specific for any stage - just placing it in a subdirectory named "stageX".

And, if we decide to change type determination from path-based to list-based - it will affect only `recurse_dir()`.
